import { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "next practice",
  description: "generated by next",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es-PE">
      <body className="antialiased">
        <header
          style={{
            backgroundColor: "Highlight",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <p>header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "cyan",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
